name: CMake C++ Tests

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Install dependencies
      run: sudo apt-get update && sudo apt-get install -y cmake g++ make

    - name: Configure CMake and load cache
      run: cmake -S . -B cmake_build

    - name: CMake Build
      run: cmake --build cmake_build

    - name: CMake Run C++ Test
      run: cd cmake_build && ctest